### ISSUE TITLE
Explanation Requested for releases syntax

### ISSUE THREAD

**Issue by defencedog** [tsukumijima/libmali-rockchip#6]
I am a user of OrangePi 3b with `bitfrost G52`. In the release page I have seen following syntax:
```
libmali-bifrost-g52-g13p0-dummy-gbm_1.9-1_arm64.deb
libmali-bifrost-g52-g13p0-dummy_1.9-1_arm64.deb
libmali-bifrost-g52-g13p0-gbm_1.9-1_arm64.deb
libmali-bifrost-g52-g13p0-wayland-gbm_1.9-1_arm64.deb
libmali-bifrost-g52-g13p0-without-cl-dummy-gbm_1.9-1_arm64.deb
libmali-bifrost-g52-g13p0-x11-gbm_1.9-1_arm64.deb
libmali-bifrost-g52-g2p0-dummy-gbm_1.9-1_arm64.deb
libmali-bifrost-g52-g2p0-dummy_1.9-1_arm64.deb
libmali-bifrost-g52-g2p0-gbm_1.9-1_arm64.deb
libmali-bifrost-g52-g2p0-wayland-gbm_1.9-1_arm64.deb
libmali-bifrost-g52-g2p0-without-cl-dummy-gbm_1.9-1_arm64.deb
libmali-bifrost-g52-g2p0-x11-gbm_1.9-1_arm64.deb

```

I cannot understand syntax used: `g13p0` `g2p0` `dummy-gbm` `gbm` `wayland-gbm` `x11-gbm`

If I am using `xfce` with 5.10.x vendor kernel (compiled with `panfrost, bitfrost` support) which release should I use?

**Comment by tsukumijima** [comment]
I only pull this code from upstream regularly, so I don't know the details.
But it looks like g13p0 is a newer driver than g2p0.
Honestly, I don't think the wayland-gbm and other variations are that different for each binary. I am using the wayland-gbm version (RK3588S environment).
