### ISSUE TITLE
Add original mali g52 code 0x7212

### ISSUE THREAD

**Issue by Mateus2022** [tsukumijima/libmali-rockchip#7]
I am using mali g52 phone with termux proot ubuntu installed libmali g52 bifrost get this root@localhost:/sdcard# eglgears_x11
arm_release_ver of this libmali is 'g2p0-01eac0', rk_so_ver is '4'.
arm_release_ver of this libmali is 'g2p0-01eac0', rk_so_ver is '4'.
arm_release_ver of this libmali is 'g2p0-01eac0', rk_so_ver is '4'.
ERROR: The DDK (built for 0x70020000 r1p0 status range [0..15]) is not compatible with this Mali GPU device, /dev/mali0 detected as 0x7212 r0p0 status 0.
Failed creating base context during DDK compatibility check.
arm_release_ver of this libmali is 'g2p0-01eac0', rk_so_ver is '4'.
EGLUT: failed to initialize EGL display
root@localhost:/sdcard#

**Comment by tsukumijima** [comment]
This user-mode driver (.so) is for plain Linux.
It is natural to assume that this user-mode driver is not supported on Termux on Android, which uses the Linux kernel but is heavily customized.

**Comment by Mateus2022** [comment]
a shame maybe in the future with some implementations in panfrost for use in android kernel standards it will be possible.
