### ISSUE TITLE
Pull the latest version

### ISSUE THREAD

**Issue by HeyMeco** [tsukumijima/libmali-rockchip#8]
Notice: JeffyCN/mirrors has been updated.

**Comment by tsukumijima** [comment]
Thanks for letting me know. This repository is automatically merged from upstream, but it seems the GitHub Actions workflow was broken. I have now fixed it.

**Comment by HeyMeco** [comment]
@tsukumijima the build seems to still have failed

**Comment by tsukumijima** [comment]
I looked at the error log and it looks like maybe the dependencies have changed, but I don't use this repository much anymore and I don't have much motivation to actively update it, so I'll leave it as it is until someone sends me a pull request.
